# Generated by Django 5.1.15 on 2026-10-03 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Projeto')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Identificador (Slug)')),
                ('categorias', models.CharField(default='acolhimento', help_text="Categorias válidas: acolhimento, saude, autoestima, empoderamento (ex: 'acolhimento,saude')", max_length=100, verbose_name='Categorias (separadas por vírgula)')),
                ('categoria_label', models.CharField(help_text="Ex: 'Saúde & Dignidade', 'Acolhimento & Moradia', 'Autoestima Feminina'", max_length=100, verbose_name='Rótulo da Categoria Principal')),
                ('resumo_impacto', models.CharField(help_text="Frase de destaque no topo do card (ex: '+37.000 Caldos Entregues', 'Hospedagem 100% Gratuita')", max_length=120, verbose_name='Destaque de Impacto')),
                ('texto_botao', models.CharField(default='Conhecer Projeto', help_text="Ex: 'Doar Bolsas / Insumos', 'Apoiar a Casa de Apoio', 'Solicitar Palestra'", max_length=60, verbose_name='Texto do Botão (CTA)')),
                ('mes_ano', models.CharField(default='Ação Permanente', help_text="Ex: 'Projeto 2026', 'Desde Jan/2026', 'Projeto Ativo', 'Encontro Mensal'", max_length=60, verbose_name='Status / Período')),
                ('imagem', models.ImageField(help_text='Foto ou banner ilustrativo do projeto.', upload_to='projetos/%Y/%m/', verbose_name='Imagem de Capa do Projeto')),
                ('alt_imagem', models.CharField(blank=True, help_text='Descrição curta para acessibilidade e leitores de tela.', max_length=200, verbose_name='Texto Alternativo da Imagem')),
                ('descricao', models.TextField(help_text='Texto curto de apresentação exibido na grade do site.', verbose_name='Descrição Resumida (Card)')),
                ('tagline_modal', models.CharField(blank=True, help_text="Citação ou lema em destaque (ex: 'A dignidade começa no cuidado.')", max_length=255, verbose_name='Frase de Efeito no Modal (Tagline)')),
                ('descricao_modal', models.TextField(blank=True, help_text='Texto introdutório ao abrir o modal com detalhes do projeto.', verbose_name='Descrição Completa no Modal')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro (0 tem prioridade máxima).', verbose_name='Ordem de Prioridade')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar o projeto sem excluí-lo.', verbose_name='Exibir no Site')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos e Ações',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SecaoProjeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text="Ex: 'Objetivo Geral', 'Objetivos Específicos', 'Como Ajudar', 'Impacto Social'", max_length=150, verbose_name='Título da Seção')),
                ('conteudo', models.TextField(help_text='Texto ou lista de tópicos. Se quiser tópicos com marcadores, coloque cada item em uma nova linha.', verbose_name='Conteúdo da Seção')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem em que esta seção aparece dentro do modal.', verbose_name='Ordem de Exibição no Modal')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='projetos.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Seção Informativa do Modal',
                'verbose_name_plural': 'Seções Informativas do Modal',
                'ordering': ['ordem'],
            },
        ),
    ]
