# Generated by Django 5.1.15 on 2026-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Instagram'),
        ),
    ]
